### ISSUE TITLE
Restructure Response Stages/Phases

### ISSUE THREAD

**Issue by Karneades** [atc-project/atc-react#279]
Hi, I also created a list of IR activities for an incident response card game called now "Defensomania", see [activities](https://github.com/Karneades/Defensomania/blob/master/cards/activities.tsv), because I missed such a list too at that time. I will try to add missing activities which I have in the card game into RE&ACT and also use your activities for the cards if something is missing, if that's ok for you? In the future, I could try to base the activity cards on your list and split that out from the game itself.

Would you mind adding a "Communication" stage and simplify containment/eradication into a "respond" category? I did that for the game because so many activities can be in both.

**Comment by yugoslavskiy** [comment]
Hello @Karneades !

Thank you for your comment and proposals!

> I will try to add missing activities which I have in the card game into RE&ACT and also use your activities for the cards if something is missing, if that's ok for you?

Absolutely. You are welcome to do that.

> Would you mind adding a "Communication" stage [...]?

We are following the [MITRE ATT&CK](https://attack.mitre.org/) philosophy, and its basic principle is that each column represents **what** we are trying to achieve (Response Stages), and each cell represents **how** we can achieve it (Response Action). 

We believe that Communication is not an objective by itself.  Communication is a method to achieve something, this way, in our paradigm, it should be on the Response Actions level, not on Response Stages.

At the same time, we would like to be as generic as possible, and customizable at the same time.  

Each company has it's own specifics requirements and procedures. 

For example, Company "A" is a huge Managed Security Service Provider, there are dozens of departments, and many of the listed Response Actions is the matter of communication with some specific Department or Team (like, you want to block some IP address — you need to communicate with Network Team). 

Company "B" is a small internal security team that does everything by themselves. Each Response Actions is a matter of actual execution of the listed steps. They don't need to communicate with any teams, rather than with Managers (incident report) and external companies (share IoC/IoA). 

Should we create a "communication" RA on each of the possible steps? We believe it should be done by the users of the Framework, as well as many other things. 

> Would you mind [...] simplify containment/eradication into a "respond" category?

well, basically, all the listed Response Stages could be unified under "respond" stage, but we would like to be more specific.

Of course, most of the listed Response Actions under Containment and Eradication stages could be executed at the same time, but there are cases when they are not. Some of the teams (most advanced ones) let a threat to stay in the environment for a little longer (after containment of some level), collecting new IoC/IoA, trying to make adversary do a mistake and provide more info that could be transformed into Threat Intelligence and be used to identify the criminal. And only when they (IR team) achieved what they want, collected enough evidence, they proceed with the Eradication stage. 

That's why we would like to keep these Response Stages separated.

**Comment by Karneades** [comment]
Thanks @yugoslavskiy for taking your time!

Fully agree, using the mentioned response stage including containment and eradication is good practice to keep track of the activities and where you are during IR.

> We believe that Communication is not an objective by itself. Communication is a method to achieve something, this way, in our paradigm, it should be on the Response Actions level, not on Response Stages.

I was not thinking of communication as a method for triggering an RA, instead I was referring to the needed communication steps during incident handling, inform management, writing a report,  communicate findings with external parties, ... but I guess it's enough to add those to the other phases, I saw one regarding writing a report in eradication.
