### ISSUE TITLE
Acronym Meaning

### ISSUE THREAD

**Issue by PolarBearGod** [atc-project/atc-react#283]
It seems like such a petty issue and my apologies but what does RE&CT actually stand for? As in, what does the acronym itself mean.

ATT&CK stands for **Adversarial Tactics, Techniques, and Common Knowledge** but it is not clear what RE&CT stands for?

**Comment by yugoslavskiy** [comment]
Hello! I think that ATT&CK doesn't rely on this acronym anymore, at least, when we were discussing this topic internally, we were not able to find the info about it on their website (even tho I remember it was there a couple of years ago).

So, RE&CT stands for RE&CT. Just RE&CT. And we believe that's OK, since it reflects the idea pretty well (:

**Comment by PolarBearGod** [comment]
Its right under their Resources > Getting Started > ATT&CK 101 Blog page...
Linked to from here: https://attack.mitre.org/resources/getting-started/
https://medium.com/mitre-attack/att-ck-101-17074d3bc62

So if you guys are just sticking with an initialism, alright.

**Comment by yugoslavskiy** [comment]
Ah, yeah. It's mentioned in the old blog posts/pdf docs ofc, but I mean they haven't mentioned it on their website (current version) and latest documents, such as [Philosophy Paper]( https://attack.mitre.org/docs/ATTACK_Design_and_Philosophy_March_2020.pdf) (March 2020). That's why I think that they have abandoned it, or just don't care anymore.
